// Immutable Provenance Chain (IPC) protocol — gRPC API.
// Prana is the reference implementation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/server/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Submitter     []byte                 `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_pkg_server_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SubmitRequest) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *SubmitRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SubmitRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockIndex    uint64                 `protobuf:"varint,3,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	BlockTime     int64                  `protobuf:"varint,4,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_pkg_server_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitResponse) GetBlockIndex() uint64 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

func (x *SubmitResponse) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_pkg_server_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{2}
}

func (x *WaitRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type AnchorProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	BlockIndex    uint64                 `protobuf:"varint,2,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	BlockTime     int64                  `protobuf:"varint,3,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	SmtProof      []byte                 `protobuf:"bytes,5,opt,name=smt_proof,json=smtProof,proto3" json:"smt_proof,omitempty"`
	Submitter     []byte                 `protobuf:"bytes,6,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Label         string                 `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorProof) Reset() {
	*x = AnchorProof{}
	mi := &file_pkg_server_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorProof) ProtoMessage() {}

func (x *AnchorProof) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorProof.ProtoReflect.Descriptor instead.
func (*AnchorProof) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{3}
}

func (x *AnchorProof) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AnchorProof) GetBlockIndex() uint64 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

func (x *AnchorProof) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *AnchorProof) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *AnchorProof) GetSmtProof() []byte {
	if x != nil {
		return x.SmtProof
	}
	return nil
}

func (x *AnchorProof) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *AnchorProof) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_pkg_server_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_server_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{5}
}

type StateRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateRoot     []byte                 `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BlockIndex    uint64                 `protobuf:"varint,2,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	Lambda1       float32                `protobuf:"fixed32,3,opt,name=lambda1,proto3" json:"lambda1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRootResponse) Reset() {
	*x = StateRootResponse{}
	mi := &file_pkg_server_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRootResponse) ProtoMessage() {}

func (x *StateRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRootResponse.ProtoReflect.Descriptor instead.
func (*StateRootResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{6}
}

func (x *StateRootResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *StateRootResponse) GetBlockIndex() uint64 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

func (x *StateRootResponse) GetLambda1() float32 {
	if x != nil {
		return x.Lambda1
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	CurrentRoot   []byte                 `protobuf:"bytes,4,opt,name=current_root,json=currentRoot,proto3" json:"current_root,omitempty"`
	Lambda1       float32                `protobuf:"fixed32,5,opt,name=lambda1,proto3" json:"lambda1,omitempty"`
	ActivePeers   uint32                 `protobuf:"varint,6,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	TotalPeers    uint32                 `protobuf:"varint,7,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	PendingHashes uint64                 `protobuf:"varint,8,opt,name=pending_hashes,json=pendingHashes,proto3" json:"pending_hashes,omitempty"`
	AvgTps        float32                `protobuf:"fixed32,9,opt,name=avg_tps,json=avgTps,proto3" json:"avg_tps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_server_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *HealthResponse) GetCurrentRoot() []byte {
	if x != nil {
		return x.CurrentRoot
	}
	return nil
}

func (x *HealthResponse) GetLambda1() float32 {
	if x != nil {
		return x.Lambda1
	}
	return 0
}

func (x *HealthResponse) GetActivePeers() uint32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *HealthResponse) GetTotalPeers() uint32 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

func (x *HealthResponse) GetPendingHashes() uint64 {
	if x != nil {
		return x.PendingHashes
	}
	return 0
}

func (x *HealthResponse) GetAvgTps() float32 {
	if x != nil {
		return x.AvgTps
	}
	return 0
}

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_pkg_server_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{8}
}

func (x *BlockRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_pkg_server_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{9}
}

func (x *BlockRange) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlockRange) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Proposer      []byte                 `protobuf:"bytes,4,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Triad         [][]byte               `protobuf:"bytes,5,rep,name=triad,proto3" json:"triad,omitempty"`
	Anchored      []*ProvenanceEntry     `protobuf:"bytes,6,rep,name=anchored,proto3" json:"anchored,omitempty"`
	Lambda1       float64                `protobuf:"fixed64,7,opt,name=lambda1,proto3" json:"lambda1,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sigs          [][]byte               `protobuf:"bytes,9,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pkg_server_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{10}
}

func (x *Block) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Block) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Block) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *Block) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *Block) GetTriad() [][]byte {
	if x != nil {
		return x.Triad
	}
	return nil
}

func (x *Block) GetAnchored() []*ProvenanceEntry {
	if x != nil {
		return x.Anchored
	}
	return nil
}

func (x *Block) GetLambda1() float64 {
	if x != nil {
		return x.Lambda1
	}
	return 0
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type ProvenanceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Submitter     []byte                 `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvenanceEntry) Reset() {
	*x = ProvenanceEntry{}
	mi := &file_pkg_server_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvenanceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvenanceEntry) ProtoMessage() {}

func (x *ProvenanceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvenanceEntry.ProtoReflect.Descriptor instead.
func (*ProvenanceEntry) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_proto_rawDescGZIP(), []int{11}
}

func (x *ProvenanceEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ProvenanceEntry) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *ProvenanceEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProvenanceEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_pkg_server_api_proto protoreflect.FileDescriptor

const file_pkg_server_api_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/server/api.proto\x12\n" +
	"provenance\"\x93\x01\n" +
	"\rSubmitRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1c\n" +
	"\tsubmitter\x18\x02 \x01(\fR\tsubmitter\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"\x84\x01\n" +
	"\x0eSubmitResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vblock_index\x18\x03 \x01(\x04R\n" +
	"blockIndex\x12\x1d\n" +
	"\n" +
	"block_time\x18\x04 \x01(\x03R\tblockTime\"!\n" +
	"\vWaitRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\xd3\x01\n" +
	"\vAnchorProof\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vblock_index\x18\x02 \x01(\x04R\n" +
	"blockIndex\x12\x1d\n" +
	"\n" +
	"block_time\x18\x03 \x01(\x03R\tblockTime\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12\x1b\n" +
	"\tsmt_proof\x18\x05 \x01(\fR\bsmtProof\x12\x1c\n" +
	"\tsubmitter\x18\x06 \x01(\fR\tsubmitter\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\"#\n" +
	"\rVerifyRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\a\n" +
	"\x05Empty\"m\n" +
	"\x11StateRootResponse\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\fR\tstateRoot\x12\x1f\n" +
	"\vblock_index\x18\x02 \x01(\x04R\n" +
	"blockIndex\x12\x18\n" +
	"\alambda1\x18\x03 \x01(\x02R\alambda1\"\xa5\x02\n" +
	"\x0eHealthResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fblock_height\x18\x03 \x01(\x04R\vblockHeight\x12!\n" +
	"\fcurrent_root\x18\x04 \x01(\fR\vcurrentRoot\x12\x18\n" +
	"\alambda1\x18\x05 \x01(\x02R\alambda1\x12!\n" +
	"\factive_peers\x18\x06 \x01(\rR\vactivePeers\x12\x1f\n" +
	"\vtotal_peers\x18\a \x01(\rR\n" +
	"totalPeers\x12%\n" +
	"\x0epending_hashes\x18\b \x01(\x04R\rpendingHashes\x12\x17\n" +
	"\aavg_tps\x18\t \x01(\x02R\x06avgTps\"$\n" +
	"\fBlockRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\"0\n" +
	"\n" +
	"BlockRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\"\x90\x02\n" +
	"\x05Block\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\fR\bprevHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12\x1a\n" +
	"\bproposer\x18\x04 \x01(\fR\bproposer\x12\x14\n" +
	"\x05triad\x18\x05 \x03(\fR\x05triad\x127\n" +
	"\banchored\x18\x06 \x03(\v2\x1b.provenance.ProvenanceEntryR\banchored\x12\x18\n" +
	"\alambda1\x18\a \x01(\x01R\alambda1\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04sigs\x18\t \x03(\fR\x04sigs\"w\n" +
	"\x0fProvenanceEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1c\n" +
	"\tsubmitter\x18\x02 \x01(\fR\tsubmitter\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label2\xd7\x03\n" +
	"\x10ProvenanceAnchor\x12C\n" +
	"\n" +
	"SubmitHash\x12\x19.provenance.SubmitRequest\x1a\x1a.provenance.SubmitResponse\x12A\n" +
	"\rWaitForAnchor\x12\x17.provenance.WaitRequest\x1a\x17.provenance.AnchorProof\x12@\n" +
	"\n" +
	"VerifyHash\x12\x19.provenance.VerifyRequest\x1a\x17.provenance.AnchorProof\x12G\n" +
	"\x13GetCurrentStateRoot\x12\x11.provenance.Empty\x1a\x1d.provenance.StateRootResponse\x12:\n" +
	"\tGetHealth\x12\x11.provenance.Empty\x1a\x1a.provenance.HealthResponse\x127\n" +
	"\bGetBlock\x12\x18.provenance.BlockRequest\x1a\x11.provenance.Block\x12;\n" +
	"\fStreamBlocks\x12\x16.provenance.BlockRange\x1a\x11.provenance.Block0\x01B8Z6github.com/had-nu/prana-provenance-chain/pkg/server/pbb\x06proto3"

var (
	file_pkg_server_api_proto_rawDescOnce sync.Once
	file_pkg_server_api_proto_rawDescData []byte
)

func file_pkg_server_api_proto_rawDescGZIP() []byte {
	file_pkg_server_api_proto_rawDescOnce.Do(func() {
		file_pkg_server_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_server_api_proto_rawDesc), len(file_pkg_server_api_proto_rawDesc)))
	})
	return file_pkg_server_api_proto_rawDescData
}

var file_pkg_server_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_server_api_proto_goTypes = []any{
	(*SubmitRequest)(nil),     // 0: provenance.SubmitRequest
	(*SubmitResponse)(nil),    // 1: provenance.SubmitResponse
	(*WaitRequest)(nil),       // 2: provenance.WaitRequest
	(*AnchorProof)(nil),       // 3: provenance.AnchorProof
	(*VerifyRequest)(nil),     // 4: provenance.VerifyRequest
	(*Empty)(nil),             // 5: provenance.Empty
	(*StateRootResponse)(nil), // 6: provenance.StateRootResponse
	(*HealthResponse)(nil),    // 7: provenance.HealthResponse
	(*BlockRequest)(nil),      // 8: provenance.BlockRequest
	(*BlockRange)(nil),        // 9: provenance.BlockRange
	(*Block)(nil),             // 10: provenance.Block
	(*ProvenanceEntry)(nil),   // 11: provenance.ProvenanceEntry
}
var file_pkg_server_api_proto_depIdxs = []int32{
	11, // 0: provenance.Block.anchored:type_name -> provenance.ProvenanceEntry
	0,  // 1: provenance.ProvenanceAnchor.SubmitHash:input_type -> provenance.SubmitRequest
	2,  // 2: provenance.ProvenanceAnchor.WaitForAnchor:input_type -> provenance.WaitRequest
	4,  // 3: provenance.ProvenanceAnchor.VerifyHash:input_type -> provenance.VerifyRequest
	5,  // 4: provenance.ProvenanceAnchor.GetCurrentStateRoot:input_type -> provenance.Empty
	5,  // 5: provenance.ProvenanceAnchor.GetHealth:input_type -> provenance.Empty
	8,  // 6: provenance.ProvenanceAnchor.GetBlock:input_type -> provenance.BlockRequest
	9,  // 7: provenance.ProvenanceAnchor.StreamBlocks:input_type -> provenance.BlockRange
	1,  // 8: provenance.ProvenanceAnchor.SubmitHash:output_type -> provenance.SubmitResponse
	3,  // 9: provenance.ProvenanceAnchor.WaitForAnchor:output_type -> provenance.AnchorProof
	3,  // 10: provenance.ProvenanceAnchor.VerifyHash:output_type -> provenance.AnchorProof
	6,  // 11: provenance.ProvenanceAnchor.GetCurrentStateRoot:output_type -> provenance.StateRootResponse
	7,  // 12: provenance.ProvenanceAnchor.GetHealth:output_type -> provenance.HealthResponse
	10, // 13: provenance.ProvenanceAnchor.GetBlock:output_type -> provenance.Block
	10, // 14: provenance.ProvenanceAnchor.StreamBlocks:output_type -> provenance.Block
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_server_api_proto_init() }
func file_pkg_server_api_proto_init() {
	if File_pkg_server_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_server_api_proto_rawDesc), len(file_pkg_server_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_server_api_proto_goTypes,
		DependencyIndexes: file_pkg_server_api_proto_depIdxs,
		MessageInfos:      file_pkg_server_api_proto_msgTypes,
	}.Build()
	File_pkg_server_api_proto = out.File
	file_pkg_server_api_proto_goTypes = nil
	file_pkg_server_api_proto_depIdxs = nil
}
