// Immutable Provenance Chain (IPC) protocol — gRPC API.
// Gleipnir is the reference implementation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pkg/server/api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvenanceAnchor_SubmitHash_FullMethodName          = "/provenance.ProvenanceAnchor/SubmitHash"
	ProvenanceAnchor_WaitForAnchor_FullMethodName       = "/provenance.ProvenanceAnchor/WaitForAnchor"
	ProvenanceAnchor_VerifyHash_FullMethodName          = "/provenance.ProvenanceAnchor/VerifyHash"
	ProvenanceAnchor_GetCurrentStateRoot_FullMethodName = "/provenance.ProvenanceAnchor/GetCurrentStateRoot"
	ProvenanceAnchor_GetHealth_FullMethodName           = "/provenance.ProvenanceAnchor/GetHealth"
	ProvenanceAnchor_GetBlock_FullMethodName            = "/provenance.ProvenanceAnchor/GetBlock"
	ProvenanceAnchor_StreamBlocks_FullMethodName        = "/provenance.ProvenanceAnchor/StreamBlocks"
)

// ProvenanceAnchorClient is the client API for ProvenanceAnchor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvenanceAnchorClient interface {
	SubmitHash(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	WaitForAnchor(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*AnchorProof, error)
	VerifyHash(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*AnchorProof, error)
	GetCurrentStateRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StateRootResponse, error)
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Block, error)
	StreamBlocks(ctx context.Context, in *BlockRange, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
}

type provenanceAnchorClient struct {
	cc grpc.ClientConnInterface
}

func NewProvenanceAnchorClient(cc grpc.ClientConnInterface) ProvenanceAnchorClient {
	return &provenanceAnchorClient{cc}
}

func (c *provenanceAnchorClient) SubmitHash(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_SubmitHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) WaitForAnchor(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*AnchorProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnchorProof)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_WaitForAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) VerifyHash(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*AnchorProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnchorProof)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_VerifyHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) GetCurrentStateRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StateRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateRootResponse)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_GetCurrentStateRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, ProvenanceAnchor_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceAnchorClient) StreamBlocks(ctx context.Context, in *BlockRange, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProvenanceAnchor_ServiceDesc.Streams[0], ProvenanceAnchor_StreamBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BlockRange, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvenanceAnchor_StreamBlocksClient = grpc.ServerStreamingClient[Block]

// ProvenanceAnchorServer is the server API for ProvenanceAnchor service.
// All implementations must embed UnimplementedProvenanceAnchorServer
// for forward compatibility.
type ProvenanceAnchorServer interface {
	SubmitHash(context.Context, *SubmitRequest) (*SubmitResponse, error)
	WaitForAnchor(context.Context, *WaitRequest) (*AnchorProof, error)
	VerifyHash(context.Context, *VerifyRequest) (*AnchorProof, error)
	GetCurrentStateRoot(context.Context, *Empty) (*StateRootResponse, error)
	GetHealth(context.Context, *Empty) (*HealthResponse, error)
	GetBlock(context.Context, *BlockRequest) (*Block, error)
	StreamBlocks(*BlockRange, grpc.ServerStreamingServer[Block]) error
	mustEmbedUnimplementedProvenanceAnchorServer()
}

// UnimplementedProvenanceAnchorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvenanceAnchorServer struct{}

func (UnimplementedProvenanceAnchorServer) SubmitHash(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHash not implemented")
}
func (UnimplementedProvenanceAnchorServer) WaitForAnchor(context.Context, *WaitRequest) (*AnchorProof, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForAnchor not implemented")
}
func (UnimplementedProvenanceAnchorServer) VerifyHash(context.Context, *VerifyRequest) (*AnchorProof, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyHash not implemented")
}
func (UnimplementedProvenanceAnchorServer) GetCurrentStateRoot(context.Context, *Empty) (*StateRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentStateRoot not implemented")
}
func (UnimplementedProvenanceAnchorServer) GetHealth(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedProvenanceAnchorServer) GetBlock(context.Context, *BlockRequest) (*Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedProvenanceAnchorServer) StreamBlocks(*BlockRange, grpc.ServerStreamingServer[Block]) error {
	return status.Error(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedProvenanceAnchorServer) mustEmbedUnimplementedProvenanceAnchorServer() {}
func (UnimplementedProvenanceAnchorServer) testEmbeddedByValue()                          {}

// UnsafeProvenanceAnchorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvenanceAnchorServer will
// result in compilation errors.
type UnsafeProvenanceAnchorServer interface {
	mustEmbedUnimplementedProvenanceAnchorServer()
}

func RegisterProvenanceAnchorServer(s grpc.ServiceRegistrar, srv ProvenanceAnchorServer) {
	// If the following call panics, it indicates UnimplementedProvenanceAnchorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvenanceAnchor_ServiceDesc, srv)
}

func _ProvenanceAnchor_SubmitHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).SubmitHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_SubmitHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).SubmitHash(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_WaitForAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).WaitForAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_WaitForAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).WaitForAnchor(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_VerifyHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).VerifyHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_VerifyHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).VerifyHash(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_GetCurrentStateRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).GetCurrentStateRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_GetCurrentStateRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).GetCurrentStateRoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceAnchorServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvenanceAnchor_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceAnchorServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvenanceAnchor_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvenanceAnchorServer).StreamBlocks(m, &grpc.GenericServerStream[BlockRange, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvenanceAnchor_StreamBlocksServer = grpc.ServerStreamingServer[Block]

// ProvenanceAnchor_ServiceDesc is the grpc.ServiceDesc for ProvenanceAnchor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvenanceAnchor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provenance.ProvenanceAnchor",
	HandlerType: (*ProvenanceAnchorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHash",
			Handler:    _ProvenanceAnchor_SubmitHash_Handler,
		},
		{
			MethodName: "WaitForAnchor",
			Handler:    _ProvenanceAnchor_WaitForAnchor_Handler,
		},
		{
			MethodName: "VerifyHash",
			Handler:    _ProvenanceAnchor_VerifyHash_Handler,
		},
		{
			MethodName: "GetCurrentStateRoot",
			Handler:    _ProvenanceAnchor_GetCurrentStateRoot_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ProvenanceAnchor_GetHealth_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _ProvenanceAnchor_GetBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBlocks",
			Handler:       _ProvenanceAnchor_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/server/api.proto",
}
